app = "social-network-frontend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    NEXT_PUBLIC_API_BASE_URL = "https://social-network-backend.fly.dev"

[env]
  NEXT_PUBLIC_API_BASE_URL = "https://social-network-backend.fly.dev"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
