import { Geist, Geist_Mono } from "next/font/google";
import { SharedWorkerProvider } from "../contexts/SharedWorkerContext";
import { NavbarProvider } from "../contexts/NavBarContext";
import {Navbar} from "./home/components/Navbar"
import AuthProvider from "../contexts/AuthContext"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <SharedWorkerProvider>
          <NavbarProvider>
            <Navbar />
            {children}
          </NavbarProvider>
        </SharedWorkerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
